"use client";

import { Check, LoaderCircle, X } from "lucide-react";
import Link from "next/link";
import { signIn } from "next-auth/react";
import { type FormEvent, useState } from "react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PasswordPolicy } from "@/modules/auth/domain/password-policy";

interface Invitation { email: string; role: string; workspaceName: string; existingAccount: boolean; expiresAt: Date | string }
export function InvitationJoinForm({ invitation, sessionEmail, token }: { invitation: Invitation; sessionEmail: string | null; token: string }) {
  const [name, setName] = useState(""); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  const callback = `/join/${token}`; const matching = sessionEmail?.toLowerCase() === invitation.email;
  async function joinExisting() { setPending(true); setError(null); try { const response = await fetch(`/api/auth/invitations/${token}/accept`, { method: "POST" }); const body = await response.json() as { data?: { workspaceSlug: string }; error?: { message: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Workspace could not be joined."); window.location.assign(`/app/${body.data.workspaceSlug}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Workspace could not be joined."); setPending(false); } }
  async function register(event: FormEvent) { event.preventDefault(); setError(null); if (password !== confirmation) { setError("Passwords do not match."); return; } if (PasswordPolicy.requirements(password).some((item) => !item.valid)) { setError("Choose a stronger password."); return; } setPending(true); try { const response = await fetch(`/api/auth/invitations/${token}/register`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, password }) }); const body = await response.json() as { data?: { email: string }; error?: { message: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Registration failed."); const result = await signIn("credentials", { email: body.data.email, password, callbackUrl: "/app", redirect: false }); if (!result?.url) throw new Error("Registered, but sign in failed."); window.location.assign(result.url); } catch (reason) { setError(reason instanceof Error ? reason.message : "Registration failed."); setPending(false); } }
  if (invitation.existingAccount) return <div className="grid gap-4"><div className="rounded-md border bg-muted/40 p-3 text-sm"><strong className="block">{invitation.email}</strong><span className="text-muted-foreground">Existing Chrono account</span></div>{matching ? <Button disabled={pending} onClick={joinExisting}>{pending ? <LoaderCircle className="animate-spin" /> : null}Join Workspace</Button> : <Button asChild><Link href={`/auth/signin?callbackUrl=${encodeURIComponent(callback)}`}>Sign in as {invitation.email}</Link></Button>}{sessionEmail && !matching ? <Alert variant="destructive"><AlertDescription>You are signed in as {sessionEmail}. Sign out and use the invited account.</AlertDescription></Alert> : null}{error ? <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert> : null}</div>;
  const requirements = PasswordPolicy.requirements(password);
  return <form className="grid gap-4" onSubmit={register}><label className="grid gap-2 text-sm font-medium">Email<Input disabled value={invitation.email} /></label><label className="grid gap-2 text-sm font-medium">Full name<Input autoFocus required value={name} onChange={(event) => setName(event.target.value)} /></label><label className="grid gap-2 text-sm font-medium">Password<Input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><label className="grid gap-2 text-sm font-medium">Confirm password<Input required type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><ul className="grid gap-1 text-xs text-muted-foreground">{requirements.map((item) => <li className="flex items-center gap-2" key={item.label}>{item.valid ? <Check className="size-3 text-emerald-500" /> : <X className="size-3" />}{item.label}</li>)}</ul>{error ? <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert> : null}<Button disabled={pending} type="submit">{pending ? <LoaderCircle className="animate-spin" /> : null}Create account and join</Button></form>;
}
